<html>
    <head>
        <title>Orden de Compra</title>
        <link rel="shortcut icon" href="http://www.boteroibanez.com/img/botero.ico">
        <link rel="stylesheet" type="text/css" href="<?php echo Conexion::ruta();?>script/estilos/estilos.css"></style>
        <link rel="stylesheet" type="text/css" href="<?php echo Conexion::ruta();?>script/estilos/estilos2.css"></style>
        <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
        <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
        <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
        <link rel="stylesheet" href="/resources/demos/style.css" />
        <script type="text/javascript">
            $(function(){
                
                $( "#datepicker" ).datepicker();

                $("#abrir").click(function(){
                        
                    $("#footer,#formulario").fadeIn();
                    });//click
                
                $("#cerrar").click(function(){
                    $("#footer,#formulario").fadeOut();
                    })
                $("#nuevo").click(function(){
                        $("#fproducto").val(" ");
                        $("#fcantidad").val(" ");
                        $("#fvu").val(" ");
                        $("#fimp").val(" ");
                        $("#f_grabar").val(" ");
                    location.href="<?php echo Conexion::ruta()?>Alm_OC&n=1";
                    });
                $("#guardar").click(function(){
                    document.form.submit();
                    });
                $("#estadod").click(function(){
                    alert("estado");
                });

                $("#sucursal").click(function(){
                    alert("sucursal");
                })

                $("#Imprimir").click(function(){
                    var id=$("#Id").val();
                   window.open("<?php echo Conexion::ruta()?>view/pdf/pdf_requi.phtml?Alm_OC="+id+"&id_centro=<?php echo $_SESSION["id_centro"]?>","Impresion" ,"width=700,height=700,scrollbars=NO"); 
                    location.href="<?php echo Conexion::ruta()?>Alm_OC&i="+id;
                });

                $("#buscar").click(function(){
                    var dato=$("#txtbuscar").val();
                    location.href="<?php echo Conexion::ruta()?>Alm_OC&b="+dato;
                })

                $("#txtbuscar").keypress(function(event){
                    if(event.which==13){
                        var dato=$("#txtbuscar").val();
                        location.href="<?php echo Conexion::ruta()?>Alm_OC&b="+dato;
                    }
                });


                 $("#activo").click(function(){
                    if($("#activo").is(":checked")){
                        $("#norequi").removeAttr("disabled");
                    }else{
                        $("#norequi").attr("disabled",true);
                    }    
                })


                 var availableTags=new Array(<?php echo $proveedores; ?>);
                $( "#Proveedor" ).autocomplete({
                        source: availableTags
                });


                });//main    
        </script>
        <script type="text/javascript">
        function eliminar(id,id_requi){
            if(confirm("Desea eliminar este detalle")){
                location.href="<?php echo Conexion::ruta()?>Alm_OC&e="+id+"&b="+id_requi;
            }
        }
        function editar(id){
            var id=$("#jid").val();
            var producto=$("#jproducto").val();
            var cantidad=$("#jcantidad").val();
            var vunitario=$("#jvu").val();
            var impuesto=$("#jimp").val();

            $("#fid").val(id);
            $("#fproducto").val(producto);
            $("#fcantidad").val(cantidad);
            $("#fvu").val(vunitario);
            $("#fimp").val(impuesto);
            $("#f_grabar").val("si2");
            $("#footer,#formulario").fadeIn();
        }

        function copiar(id,id_requi){
            if(confirm("Esta seguro copiar esta fila?")){
             location.href="<?php echo Conexion::ruta()?>Alm_OC&Con="+id+"&id="+id_requi;   
            }else{
                $(".ck").removeAttr("checked");
            }
        }

        </script>
    </head>
    <body>
        <div id="header">
            <div id="logo">
                
            </div>
            <div id="menu">
                <?php include"view/Menu.phtml";?>
            </div>
             <div id="sesion">
            <a href="<?php echo Conexion::ruta()?>cerrar"><img class="cerrar_c" src="<?php echo Conexion::ruta()?>images/cerrar.png"></a><br>
            <?php echo ucwords($_SESSION["nombre"]);?><br>
                <strong><?php echo $res[0]["Centro_costo"];?></strong>
            </div>
        </div>
        <div id="linea"></div>
        <form action="" method="POST" name="form">
        <div id="lateral">
            <ul>
                <li><img title="Nuevo" id="nuevo" class="imagen" src="<?php echo Conexion::ruta()?>images/agregar.jpg"></li>
                <li><img title="Guardar" class="imagen" src="<?php echo Conexion::ruta()?>images/guardar.png" id="guardar">
                    <input type="hidden" name="grabar" value="si"></li>
                <li><img title="Imprimir" id="Imprimir" class="imagen" src="<?php echo Conexion::ruta()?>images/impresora.png"></li>
                <li><img title="Buscar" class="imagen" id="buscar" src="<?php echo Conexion::ruta()?>images/buscar.png"></li>
                <li><input type="text" name="txtbuscar" size=10 id="txtbuscar"></li>
            </ul>
        </div>
        <div id="contenido">
            <h2>Orden de Compra</h2>
            
            <div class="caja">
               <table>
                <tr>
                    <td><span>Id</span></td>
                    <td><input type="text" name="Id" class="tam" id="Id" value="<?php echo $d[0]["Consecutivo"]?>" readonly></td>
                </tr>
                <tr>
                    <td><span>Estadodoc</span></td>
                    <td><input type="text" name="Estadodoc" value="<?php echo $d[0]["Lista"]?>" class="tam" readonly></td>
                </tr>
                <tr>
                    <td><span>Festadodoc</span></td>
                    <td><input type="text" name="Festadodoc" <?php echo $imp;?> class="tam" value="<?php echo $d[0]["Festadodoc"]?>" readonly></td>
                </tr>
                <tr>
                    <td><span>Sucursal</span></td>
                    <td><input type="text" name="sucursal" <?php echo $imp;?> class="tam" value="<?php echo $d[0]["Nombre"]?>" readonly></td>
                </tr>
                <tr>
                    <td><span>Centrocosto</span></td>
                    <td><input type="text" name="centrocosto" <?php echo $imp;?> class="tam" value="<?php echo $d[0]["Centro_costo"]?>" readonly></td>
                </tr>
            </table>
          
            </div>
            
            <div class="caja">
               <table>
                <tr>
                    <td><span>Norequi</span></td>
                    <td><input type="text" name="norequi" id="norequi" <?php echo $imp;?> class="tam" disabled value="<?php echo $d[0]["Norequi"]?>"></td>
                    <td><input type="checkbox" name="activo" id="activo"></td>
                </tr>
                <tr>
                    <td><span>Tiempo de entrega</span></td>
                    <td><input type="text" name="Tentrega" <?php echo $imp;?> class="tam" value="<?php echo $d[0]["Tiempo_entrega"]?>"></td>
                </tr>
                    <tr>
                    <td><span>Tipopago</span></td>
                    <td>
                        <select name="Tpago" <?php echo $imp;?> class="tam" >
                            <option value='0'>Seleccione</option>
                            <?php
                            foreach ($listas as $k => $valor) {
                                if($listas[$k]["Id_lista"]==$d[0]["Tipo_pago"]){
                                 ?>
                                    <option selected="selected" value="<?php echo $listas[$k]['Id_lista']?>"><?php echo $listas[$k]["Lista"]?></option>   
                                 <?php   
                                }else{
                                ?>
                                    <option value="<?php echo $listas[$k]['Id_lista']?>"><?php echo $listas[$k]["Lista"]?></option>
                                <?php        
                                }
                            }
                            ?>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td><span>Proveedor</span></td>
                    <td><input type="text" name="Proveedor" id="Proveedor" class="tam" <?php echo $imp;?> value="<?php echo $d[0]["Proveedor"]?>">
                    </td>
                </tr>
                <tr>
                    <td><span>Transportado</span></td>
                    <td><input type="text" name="Transportado" class="tam" <?php echo $imp;?> value="<?php echo $d[0]["Transportado"]?>"></td>
                </tr>
                 </table>   
            </div>
            <div class="caja">
                 <table>    
                    <tr>
                        <td><span>Lugar Entrega</span></td>
                        <td><input type="text" name="Lentrega" class="tam" <?php echo $imp;?> value="<?php echo $d[0]["Lugar_entrega"]?>"></td>
                    </tr>
                    <tr>
                        <td><span>Estado proceso</span></td>
                        <td><input type="hidden" name="Estadoproceso" class="tam" <?php echo $imp;?> value="<?php echo $d[0]["Estado_proceso"]?>">
                            <select name="Estadoproceso" <?php echo $imp;?> class="tam" >
                            <option value="0">Seleccione</option>
                            <?php
                            foreach ($estado as $k => $valor) {
                                if($estado[$k]["Id_lista"]==$d[0]["Estado_proceso"]){
                                 ?>
                                    <option selected="selected" value="<?php echo $estado[$k]['Id_lista']?>"><?php echo $estado[$k]["Lista"]?></option>   
                                 <?php   
                                }else{
                                ?>
                                    <option value="<?php echo $estado[$k]['Id_lista']?>"><?php echo $estado[$k]["Lista"]?></option>
                                <?php        
                                }
                            }
                            ?>
                        </select>

                        </td>
                    </tr>
                    <tr>
                        <td><span>Observaciones</span></td>
                        <td><textarea name="Observaciones" <?php echo $imp;?> class="tam"><?php echo $d[0]["Observaciones"]?></textarea></td>
                    </tr>
                 </table>   
            </div>
            <div id="boton">
            <a href="#" id="<?php echo $bt;?>" style="color: rgb(0,43,87);"><img  title="Agregar Detalle" id="nuevo" class="imagen" src="<?php echo Conexion::ruta()?>images/detalle.png">
            </div>
            </form>      
            <div id="tabla">

            <table align="center" class="bordered">
                <thead>
                    <th>Producto</th>
                    <th>Cantidad</th>
                    <th>Vunitario</th>
                    <th>Impuesto</th>
                    <th>Vneto</th>
                    <th>Vtotal</th>
                    <th>Editar</th>
                    <th>Eliminar</td>
                    <th>Copiar</td>
                </thead>
                
                    <?php
                    for($i=0;$i<sizeof($detalle);$i++){
                        ?>
                        <tr>
                            <td><?php echo $detalle[$i]["Producto"]?></td>
                            <td><?php echo $detalle[$i]["Cantidad"]?></td>
                            <td><?php echo $detalle[$i]["Vu"]?></td>
                            <td><?php echo $detalle[$i]["Imp"]?></td>
                            <td><?php echo "$ ".number_format($detalle[$i]["Vn"],3,",",".")?></td>
                            <td><?php echo "$ ".number_format($detalle[$i]["Vt"],3,",",".")?></td>
                            <td><img title="Editar" class="icono2" src="<?php echo Conexion::ruta()?>images/editar.jpg" onclick="editar('<?php echo $detalle[$i]["Id"]?>')"></td>
                            <td><img title="Eliminar" class="icono2" src="<?php echo Conexion::ruta()?>images/eliminar.png" onclick="eliminar('<?php echo $detalle[$i]["Id"]?>','<?php echo $detalle[$i]["Id_oc"]?>')"></td>
                            <td><input type="checkbox" class="ck" onclick="copiar('<?php echo $detalle[$i]["Id"]?>','<?php echo $detalle[$i]["Id_oc"]?>');"></td>

                        <input type="hidden" id="jid"  value="<?php echo $detalle[$i]["Id"]?>">
                        <input type="hidden" id="jproducto"  value="<?php echo $detalle[$i]["Producto"]?>">
                        <input type="hidden" id="jcantidad" value="<?php echo $detalle[$i]["Cantidad"]?>">
                        <input type="hidden" id="jvu" value="<?php echo $detalle[$i]["Vu"]?>">
                        <input type="hidden" id="jimp" value="<?php echo $detalle[$i]["Imp"]?>">
                        <input type="hidden" id="jvn" value="<?php echo $detalle[$i]["Vn"]?>">
                        <input type="hidden" id="jvt" value="<?php echo $detalle[$i]["Vt"]?>">
                        </tr>        
                        <?php
                    }
                    ?>
                    
            </table>
        </div>

        </div>
        
        <div id="footer">
                <div id="formulario">
                    <li>Equipos</li>
                    <form action="" method=post name="formulario">
                    <label>Id</label>
                    <input type="text" name="Id_requisicion" value="<?php echo $d[0]["Consecutivo"]?>" readonly>
                    <br>
                    <label>Producto</label>
                    <input name="producto" type="text" id="fproducto">
                        <br>
                    <label>Cantidad</label>
                    <input type="text" name="cantidad" id="fcantidad">
                    <br>
                    <label>Valor unitario</label>
                    <input type="text" name="vunitario" id="fvu">
                    <br>
                    <label>Impuesto</label>
                    <input type="text" name="impuesto" id="fimp">
                    <br>    
                        <br>
                    <input type="submit" name="guardar" value="Guardar">
                    <input type="hidden" id="f_grabar" name="grabar_formu" value="si">
                    <input type="hidden" name="fid" id="fid" value="">
                    <a href="#" id="cerrar">Cerrar</a>
                </form>
            </div>  
        </div>
        
    </body>
</html>
