<html>
    <head>
        <title>Ubicacion</title>
        <meta charset='utf-8'>
        <link rel="shortcut icon" href="http://www.boteroibanez.com/img/botero.ico">
        <link rel="stylesheet" type="text/css" href="<?php echo Conexion::ruta();?>script/estilos/estilos.css"></style>
        <link rel="stylesheet" type="text/css" href="<?php echo Conexion::ruta();?>script/estilos/estilos2.css"></style>
        <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
        <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
        <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
        <link rel="stylesheet" href="/resources/demos/style.css" />
        <script type="text/javascript">
            $(function(){
                 $("#logo").click(function(){
                    location.href="<?php echo Conexion::ruta();?>home";
                })
                $( "#datepicker" ).datepicker();

                $("#abrir").click(function(){
                        
                    $("#footer,#formulario").fadeIn();
                    });//click
                
                $("#cerrar").click(function(){
                    $("#footer,#formulario").fadeOut();
                    });

                $("#nuevo").click(function(){
                        $("#fproducto").val(" ");
                        $("#fcantidad").val(" ");
                        $("#fvu").val(" ");
                        $("#fimp").val(" ");
                        $("#f_grabar").val(" ");
                    location.href="<?php echo Conexion::ruta()?>Requisicion?n=1";
                    });
                $("#guardar").click(function(){
                    document.form.submit();
                    });

                $("#Imprimir").click(function(){
                    var id=$("#Id").val();
                    window.open("<?php echo Conexion::ruta()?>view/pdf/pdf_requi.phtml?Requi="+id+"&id_centro=<?php echo $_SESSION["id_centro"]?>","Impresion" ,"width=700,height=700,scrollbars=NO"); 
                    location.href="<?php echo Conexion::ruta()?>Requisicion?i="+id;

                })
                $("#estadod").click(function(){
                    alert("estado");
                });

                $("#sucursal").click(function(){
                    alert("sucursal");
                })

                $("#buscar").click(function(){
                    var dato=$("#txtbuscar").val();
                    if(!dato==0){
                    location.href="<?php echo Conexion::ruta()?>Requisicion?b="+dato;    
                    }
                })

                $("#txtbuscar").keypress(function(event){
                    if(event.which==13){
                        var dato=$("#txtbuscar").val();
                        var arreglo=dato.split(",");

                        if(arreglo[0]=="ver" && arreglo[1].length > 0){
                            window.open("<?php echo Conexion::ruta()?>view/bRequisiciones.phtml?num="+arreglo[1]+"&centro="+<?php echo $_SESSION["id_centro"];?>, this.target, 'width=700,height=600');
                        }
                        else{
                            location.href="<?php echo Conexion::ruta()?>Requisicion?b="+dato;
                        }
                    }
                    
                });

                var availableTags=new Array(<?php echo $persona; ?>);
                $( "#auto" ).autocomplete({
                        source: availableTags
                });

                var availableTags2=new Array(<?php echo $productos; ?>);
                $( "#producto" ).autocomplete({
                        source: availableTags2
                });


                });//main    
        </script>
        <script type="text/javascript">
        function eliminar(id,id_requi){
            if(confirm("Desea eliminar este detalle")){
                location.href="<?php echo Conexion::ruta()?>Requisicion?e="+id+"&b="+id_requi;
            }
        }
        function editar(id,requi,producto,cantidad,Vu,imp){
            $("#fproducto").val(producto);
            $("#fcantidad").val(cantidad);
            $("#fvu").val(Vu);
            $("#fimp").val(imp);
            $("#f_grabar").val("si2");
            $("#fid").val(id);
            $("#footer,#formulario").fadeIn();
        }

        function copiar(id,id_requi){
            if(confirm("Esta seguro copiar esta fila?")){
             location.href="<?php echo Conexion::ruta()?>Requisicion?Con="+id+"&id="+id_requi;   
            }else{
                $(".ck").removeAttr("checked");
            }
        }

        </script>
    </head>
    <body>
        <div id="header">
            <div id="logo">
                
            </div>
            <div id="menu">
                <?php include"view/Menu.phtml";?>
            </div>

             <div id="sesion">
                <a href="<?php echo Conexion::ruta()?>cerrar" title="Cerrar Sesion"><img class="cerrar_c" src="<?php echo Conexion::ruta()?>images/cerrar.png"></a><br>
                <?php echo ucwords($_SESSION["nombre"]);?><br>
                <strong><?php echo $centro;?></strong>
            </div>
        </div>
        <div id="linea"></div>
        <div id="espacio"></div>
        <form action="" method="POST" name="form">
        <div id="lateral">
            <ul>
                <li><img title="Nuevo" id="nuevo" class="imagen" src="<?php echo Conexion::ruta()?>images/agregar.jpg"></li>
                <li><img title="Guardar" class="imagen" src="<?php echo Conexion::ruta()?>images/guardar.png" id="guardar">
                    <input type="hidden" name="grabar" value="si"></li>
                <li><img title="Imprimir" id="Imprimir" class="imagen" src="<?php echo Conexion::ruta()?>images/impresora.png"></li>
                <li><img title="Buscar" class="imagen" id="buscar" src="<?php echo Conexion::ruta()?>images/buscar.png"></li>
                <li><input type="text" name="txtbuscar" size=10 id="txtbuscar"></li>
            </ul>
        </div>
        <div id="contenido">
            <h2>Ubicación</h2>
                       
        </div>
        
    </body>
</html>

