<?php
class ajax {
	private $productos=array();
    private $consumo=array();
    private $trabajo=array();
    private $detalle=array();
    private $mante=array();
    private $equipos=array();
    private $historial=array();
    private $pagos=array();
    private $examen=array();
    private $reconocimiento=array();

	public function conectar(){
	    $arcConexion="../lib/GIO.ini";
        $datos = parse_ini_file($arcConexion,true);
        
        $conexion=mysql_connect($datos["database_host"],$datos["database_user"],$datos["database_pass"]);
        mysql_select_db($datos["database_name"]);

        return $conexion;
	}

    public function get_productos(){
        $this->conectar();
        $sql="SELECT * from G_producto;";
        $res=mysql_query($sql);

        while($row=mysql_fetch_assoc($res)){
            $this->productos[]=$row;
        }

        return $this->productos;
    }

	public function get_detalle_ausencia($id){
        $this->conectar();
        $sql="SELECT * from Rh_ausentismo where Id=$id";
        $res=mysql_query($sql);

        while($row=mysql_fetch_assoc($res)){
            $this->consumo[]=$row;
        }

        return $this->consumo;
    }

    public function get_detalle_ben($id){
        $this->conectar();
        $sql="SELECT * from Rh_beneficiarios where Id=$id";
        $res=mysql_query($sql);

        while($row=mysql_fetch_assoc($res)){
            $this->trabajo[]=$row;

        }   
        return $this->trabajo;
    }

    public function get_detalle_dotacion($id){
        $this->conectar();
        $sql="SELECT * from Rh_infdotacion where Id=$id";
        $res=mysql_query($sql);

        while($row=mysql_fetch_assoc($res)){
            $this->mante[]=$row;

        }   
        return $this->mante;   
    }


     public function get_detalle_estudio($id){
        $this->conectar();
        $sql="SELECT * from Rh_estudios where Id=$id";
        $res=mysql_query($sql);

        while($row=mysql_fetch_assoc($res)){
            $this->equipos[]=$row;

        }   
        return $this->equipos;
    }

    public function get_detalle_historial($id){
        $this->conectar();
        $sql="SELECT * from Rh_hislaboral where Id=$id";
        $res=mysql_query($sql);

        while($row=mysql_fetch_assoc($res)){
            $this->historial[]=$row;

        }   
        return $this->historial;
    }

    public function get_detalle_pagos($id){
        $this->conectar();
        $sql="SELECT * from Rh_pagosadd where Id=$id";
        $res=mysql_query($sql);

        while($row=mysql_fetch_assoc($res)){
            $this->pagos[]=$row;

        }   
        return $this->pagos;
    }

    public function get_detalle_examen($id){
        $this->conectar();
        $sql="SELECT * from Rh_examenes where Id=$id";
        $res=mysql_query($sql);

        while($row=mysql_fetch_assoc($res)){
            $this->examen[]=$row;

        }   
        return $this->examen;
    }

    public function get_detalle_reconocimiento($id){
        $this->conectar();
        $sql="SELECT * from Rh_estimulos where Id=$id";
        $res=mysql_query($sql);

        while($row=mysql_fetch_assoc($res)){
            $this->reconocimiento[]=$row;

        }   
        return $this->reconocimiento;
    }

}

$obj=new ajax;


if(isset($_POST)){
    $productos=$obj->get_productos();
	switch ($_POST["tipo"]) {
		case 'Ausencia':
            $ausencia=$obj->get_detalle_ausencia($_POST["id"]);
            echo json_encode($ausencia);
            
			break;
        
		case 'Beneficiarios':
            $ben=$obj->get_detalle_ben($_POST["id"]);
            echo json_encode($ben);
			break;
        
		case 'Dotacion':
            $dotacion=$obj->get_detalle_dotacion($_POST["id"]);
            echo json_encode($dotacion);
			break;

        case 'Estudios':
            $estudios=$obj->get_detalle_estudio($_POST["id"]);
            echo json_encode($estudios);
            break;

        case 'Historial':
            $historial=$obj->get_detalle_historial($_POST["id"]);
            echo json_encode($historial);
            break;

        case 'Pagos':
            $pagos=$obj->get_detalle_pagos($_POST["id"]);
            echo json_encode($pagos);
            break;

         case 'Examen':
            $examen=$obj->get_detalle_examen($_POST["id"]);
            echo json_encode($examen);
            break;

        case 'Reconocimiento':
            $reconocimiento=$obj->get_detalle_reconocimiento($_POST["id"]);
            echo json_encode($reconocimiento);
            break;

    }
}

?>




