<html>
    <head>
        <title>Equipos</title>
        <link rel="shortcut icon" href="http://www.boteroibanez.com/img/botero.ico">
        <link rel="stylesheet" type="text/css" href="<?php echo Conexion::ruta();?>script/estilos/estilos.css"></style>
        <link rel="stylesheet" type="text/css" href="<?php echo Conexion::ruta();?>script/estilos/estilos2.css"></style>
        <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
        <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
        <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
        <link rel="stylesheet" href="/resources/demos/style.css" />
        <script type="text/javascript">
            $(function(){
                
                $( "#datepicker" ).datepicker();

                $("#abrir").click(function(){
                        
                    $("#footer,#formulario").fadeIn();
                    });//click
                
                $("#cerrar").click(function(){
                    $("#footer,#formulario").fadeOut();
                    })
                $("#nuevo").click(function(){
                        $("#fproducto").val(" ");
                        $("#fcantidad").val(" ");
                        $("#fvu").val(" ");
                        $("#fimp").val(" ");
                        $("#f_grabar").val(" ");
                    location.href="<?php echo Conexion::ruta()?>Alm_Equipos&n=1";
                    });
                $("#guardar").click(function(){
                    document.form.submit();
                    });
                $("#estadod").click(function(){
                    alert("estado");
                });

                $("#sucursal").click(function(){
                    alert("sucursal");
                })

                $("#buscar").click(function(){
                    var dato=$("#txtbuscar").val();
                    location.href="<?php echo Conexion::ruta()?>Alm_Equipos&b2="+dato;

                })

                $("#txtbuscar").keypress(function(event){
                    if(event.which==13){
                        var dato=$("#txtbuscar").val();
                       location.href="<?php echo Conexion::ruta()?>Alm_Equipos&b2="+dato;
                    }
                });

                var availableTags=new Array(<?php echo $proyectos; ?>);
                $( "#Proyecto" ).autocomplete({
                        source: availableTags
                });


                });//main    
        </script>
        <script type="text/javascript">
        function eliminar(id,id_requi){
            if(confirm("Desea eliminar este detalle")){
                location.href="<?php echo Conexion::ruta()?>Alm_Equipos&e="+id+"&b="+id_requi;
            }
        }
        function editar(id){
            var id=$("#jid").val();
            var producto=$("#jproducto").val();
            var cantidad=$("#jcantidad").val();
            var vunitario=$("#jvu").val();
            var impuesto=$("#jimp").val();

            $("#fid").val(id);
            $("#fproducto").val(producto);
            $("#fcantidad").val(cantidad);
            $("#fvu").val(vunitario);
            $("#fimp").val(impuesto);
            $("#f_grabar").val("si2");
            $("#footer,#formulario").fadeIn();

        }

        </script>
    </head>
    <body>
        <div id="header">
            <div id="logo">
                
            </div>
            <div id="menu">
                <?php include"view/Menu.phtml";?>
            </div>
             <div id="sesion">
            <a href="<?php echo Conexion::ruta()?>cerrar"><img class="cerrar_c" src="<?php echo Conexion::ruta()?>images/cerrar.png"></a><br>
            <?php echo ucwords($_SESSION["Nombre"]);?><br>
                <strong><?php echo $centro;?></strong>
            </div>
        </div>
        <div id="linea"></div>
        <form action="" method="POST" name="form" enctype="multipart/form-data">
        <div id="lateral">
            <ul>
                <li><img title="Nuevo" id="nuevo" class="imagen" src="<?php echo Conexion::ruta()?>images/agregar.jpg"></li>
                <li><img title="Guardar" class="imagen" src="<?php echo Conexion::ruta()?>images/guardar.png" id="guardar">
                    <input type="hidden" name="grabar" value="si"></li>
                <li><img title="Imprimir" class="imagen" src="<?php echo Conexion::ruta()?>images/impresora.png"></li>
                <li><img title="Buscar" class="imagen" id="buscar" src="<?php echo Conexion::ruta()?>images/buscar.png"></li>
                <li><input type="text" name="txtbuscar" size=10 id="txtbuscar"></li>
            </ul>
        </div>
        <div id="contenido">
            <h2>Equipos</h2>
            
            <div class="caja">
               <table>
                <tr>
                    <td><span>Id</span></td>
                    <td><input type="text" name="Id" value="<?php echo (isset($d[0]["Consecutivo"]))?$d[0]["Consecutivo"]:"";?>" readonly></td>
                </tr>
                
                <tr>
                    <td><span>Sucursal</span></td>
                    <td><input type="text" name="Proyecto" <?php echo (isset($imp))?$imp:"";?> value="<?php echo (isset($d[0]["Sucursal"]))?$d[0]["Sucursal"]:"";?>"></td>
                </tr>
                <tr>
                    <td><span>Centocosto</span></td>
                    <td><input type="text" name="CentroCosto" <?php echo (isset($imp))?$imp:"";?> value="<?php echo (isset($d[0]["Centro_costo"]))?$d[0]["Centro_costo"]:"";?>"></td>
                </tr>
                <tr>
                    <td><span>Tipo</span></td>
                    <td><input type="text" name="Tipo" <?php echo (isset($imp))?$imp:"";?> id="Tipo" value="<?php echo (isset($d[0]["Tipo"]))?$d[0]["Tipo"]:"";?>"></td>
                </tr>
		<tr>
                    <td><span>Capacidad Trabajo</span></td>
                    <td><input type="text" name="Capacidad" <?php echo (isset($imp))?$imp:"";?> id="Capacidad" value="<?php echo (isset($d[0]["Capacidad"]))?$d[0]["Capacidad"]:"";?>"></td>
                </tr>
		<tr>
                    <td><span>No motor</span></td>
                    <td><input type="text" name="Nomotor" <?php echo (isset($imp))?$imp:"";?> id="Capacidad" value="<?php echo (isset($d[0]["Nomotor"]))?$d[0]["Nomotor"]:"";?>"></td>
                </tr>
		<tr>
                    <td><span>Alto</span></td>
                    <td><input type="text" name="Alto" <?php echo (isset($imp))?$imp:"";?> id="Capacidad" value="<?php echo (isset($d[0]["Alto"]))?$d[0]["Alto"]:"";?>"></td>
                </tr>
		<tr>
                    <td><span>Capacidad Tanque(Gal)</span></td>
                    <td><input type="text" name="Capacidadg" <?php echo (isset($imp))?$imp:"";?> id="Capacidadg" value="<?php echo (isset($d[0]["Capacidadg"]))?$d[0]["Capacidadg"]:"";?>"></td>
                </tr>
            </table>
          
            </div>
            
            <div class="caja">
               <table>
                
                <tr>

                    <td><span>Codigo</span></td>
                    <td><input type="text" name="Codigo" <?php echo (isset($imp))?$imp:"";?> value="<?php echo (isset($d[0]["Codigo"]))?$d[0]["Codigo"]:"";?>"></td>
                </tr>
		<tr>
                    <td><span>Serial</span></td>
                    <td><input type="text" name="Serial" <?php echo (isset($imp))?$imp:"";?> value="<?php echo (isset($d[0]["Serial"]))?$d[0]["Serial"]:"";?>"></td>
                </tr>
                <tr>
                    <td><span>Valor</span></td>
                    <td><input type="text" name="Valor" <?php echo (isset($imp))?$imp:"";?> value="<?php echo (isset($d[0]["Valor"]))?$d[0]["Valor"]:"";?>"></td>
                </tr>
		<tr>
                    <td><span>Fabricacion</span></td>
                    <td><input type="text" name="Fabricacion" <?php echo (isset($imp))?$imp:"";?> value="<?php echo (isset($d[0]["Fabricacion"]))?$d[0]["Fabricacion"]:"";?>"></td>
                </tr>
                <tr>
                        <td><span>Marca</span></td>
                        <td>
                            <select name="Marca" <?php echo (isset($imp))?$imp:"";?> class="tam">
                            <option value="0">Seleccione</option>
                            <?php
                            foreach ($marca as $k => $valor) {
                                if($marca[$k]["No"]==$d[0]["Marca"]){
                                 ?>
                                    <option selected="selected" value="<?php echo $marca[$k]['No']?>"><?php echo $marca[$k]["Lista"]?></option>   
                                 <?php   
                                }else{
                                ?>
                                    <option value="<?php echo $marca[$k]['No']?>"><?php echo $marca[$k]["Lista"]?></option>
                                <?php        
                                }
                            }
                            ?>
                        </select>

                        </td>
                    </tr>
                    <tr>
                        <td><span>Foto</span></td>
                        <td><input type="file" name="foto" style="width:150px"></td>
                     </tr>
		    <tr>
			    <td><span>Peso Cert</span></td>
			    <td><input type="text" name="Pesocert" <?php echo (isset($imp))?$imp:"";?> value="<?php echo (isset($d[0]["Pesocert"]))?$d[0]["Pesocert"]:"";?>"></td>
		    </tr>
		    <tr>
			    <td><span>Ancho</span></td>
			    <td><input type="text" name="Ancho" <?php echo (isset($imp))?$imp:"";?> value="<?php echo (isset($d[0]["Ancho"]))?$d[0]["Ancho"]:"";?>"></td>
		    </tr>
                 </table>   
            </div>
            <div class="caja">
                 <table> 

		<tr>

                    <td><span>Nombre</span></td>
                    <td><input type="text" name="Nombre" <?php echo (isset($imp))?$imp:"";?> value="<?php echo (isset($d[0]["Nombre"]))?$d[0]["Nombre"]:"";?>"></td>
                </tr>
                 <tr>
                        <td><span>Modelo</span></td>
                        <td>
                            <select name="Modelo" <?php echo (isset($imp))?$imp:"";?> class="tam">
                            <option value="0">Seleccione</option>
                            <?php
                            foreach ($modelo as $k => $valor) {
                                if($modelo[$k]["No"]==$d[0]["Modelo"]){
                                 ?>
                                    <option selected="selected" value="<?php echo $modelo[$k]['No']?>"><?php echo $modelo[$k]["Lista"]?></option>   
                                 <?php   
                                }else{
                                ?>
                                    <option value="<?php echo $modelo[$k]['No']?>"><?php echo $modelo[$k]["Lista"]?></option>
                                <?php        
                                }
                            }
                            ?>
                        </select>
                        </td>
                    </tr>   
                    <tr>
                        <td><span>Propiedad</span></td>
                        <td>

                            <select name="Propiedad" <?php echo (isset($imp))?$imp:"";?> class="tam">
                            <option value="0">Seleccione</option>
                            <?php
                            foreach ($propiedad as $k => $valor) {
                                if($propiedad[$k]["Numeracion"]==$d[0]["Propiedad"]){
                                 ?>
                                    <option selected="selected" value="<?php echo $propiedad[$k]['Numeracion']?>"><?php echo $propiedad[$k]["Lista"]?></option>   
                                 <?php   
                                }else{
                                ?>
                                    <option value="<?php echo $propiedad[$k]['Numeracion']?>"><?php echo $propiedad[$k]["Lista"]?></option>
                                <?php        
                                }
                            }
                            ?>
                        </select>
                        </td>
                    </tr>
                    <tr>
                        <td><span>Ubicacion</span></td>
                        <td>
                         <select name="Localizacion" <?php echo (isset($imp))?$imp:"";?> class="tam">
                            <option value="0">Seleccione</option>
                            <?php
                            foreach ($localizacion as $j => $valor) {
                                if($localizacion[$j]["Numeracion"]==$d[0]["Localizacion"]){
                                 ?>
                                    <option selected="selected" value="<?php echo $localizacion[$j]['Numeracion']?>"><?php echo $localizacion[$j]["Lista"]?></option>   
                                 <?php   
                                }else{
                                ?>
                                    <option value="<?php echo $localizacion[$j]['Numeracion']?>"><?php echo $localizacion[$j]["Lista"]?></option>
                                <?php        
                                }
                            }
                            ?>
                        </select>
                        </td>
                     </tr>

		<tr>
                    <td><span>Decl Import</span></td>
                    <td><input type="text" name="Declaracion" <?php echo (isset($imp))?$imp:"";?> value="<?php echo (isset($d[0]["Declaracion"]))?$d[0]["Declaracion"]:"";?>"></td>
                </tr>

		<tr>
                    <td><span>Fecha R</span></td>
                    <td><input type="text" name="Fr" readonly <?php echo (isset($imp))?$imp:"";?> value="<?php echo (isset($d[0]["Fr"]))?$d[0]["Fr"]:"";?>"></td>
                </tr>
		<tr>
		    <td><span>Peso Maqui</span></td>
		    <td><input type="text" name="Pesomaq" <?php echo (isset($imp))?$imp:"";?> value="<?php echo (isset($d[0]["Pesomaq"]))?$d[0]["Pesomaq"]:"";?>"></td>
		</tr>
		<tr>
		    <td><span>Largo</span></td>
		    <td><input type="text" name="Largo" <?php echo (isset($imp))?$imp:"";?> value="<?php echo (isset($d[0]["Largo"]))?$d[0]["Largo"]:"";?>"></td>
		</tr>
                    
                   
                 </table>   
            </div>
            <div id="boton">
            <!--<a href="#" id="abrir" style="color: rgb(0,43,87);"><img title="Agregar Detalle" id="nuevo" class="imagen" src="<?php echo Conexion::ruta()?>images/detalle.png"></a>-->
            </div>
            </form>      
            <div id="tabla">

            <table align="center" class="bordered">
                <thead>
                    <th>Producto</th>
                    <th>Cantidad</th>
                    <th>Vunitario</th>
                    <th>Impuesto</th>
                    <th>Vneto</th>
                    <th>Vtotal</th>
                    <th>Editar</th>
                    <th>Eliminar</td>
                </thead>
                
                    <?php
                    for($i=0;$i<sizeof($detalle);$i++){
                        ?>
                        <tr>
                            <td><?php echo $detalle[$i]["Producto"]?></td>
                            <td><?php echo $detalle[$i]["Cantidad"]?></td>
                            <td><?php echo $detalle[$i]["Vu"]?></td>
                            <td><?php echo $detalle[$i]["Imp"]?></td>
                            <td><?php echo "$ ".number_format($detalle[$i]["Vn"],3,",",".")?></td>
                            <td><?php echo "$ ".number_format($detalle[$i]["Vt"],3,",",".")?></td>
                            <td><img title="Editar" class="icono2" src="<?php echo Conexion::ruta()?>images/editar.jpg" onclick="editar('<?php echo $detalle[$i]["Id"]?>')"></td>
                            <td><img title="Eliminar" class="icono2" src="<?php echo Conexion::ruta()?>images/eliminar.png" onclick="eliminar('<?php echo $detalle[$i]["Id"]?>','<?php echo $detalle[$i]["Id_Requisicion"]?>')"></td>
                        <input type="hidden" id="jid"  value="<?php echo $detalle[$i]["Id"]?>">
                        <input type="hidden" id="jproducto"  value="<?php echo $detalle[$i]["Producto"]?>">
                        <input type="hidden" id="jcantidad" value="<?php echo $detalle[$i]["Cantidad"]?>">
                        <input type="hidden" id="jvu" value="<?php echo $detalle[$i]["Vu"]?>">
                        <input type="hidden" id="jimp" value="<?php echo $detalle[$i]["Imp"]?>">
                        <input type="hidden" id="jvn" value="<?php echo $detalle[$i]["Vn"]?>">
                        <input type="hidden" id="jvt" value="<?php echo $detalle[$i]["Vt"]?>">
                        </tr>        
                        <?php
                    }
                    ?>
                    
            </table>
        </div>
        <div id="paginador">
            <?php
            if(isset($_GET["error"])){
                switch ($_GET["error"]) {
                    case '1':
                        echo "<h3 style='color:red'>El serial ya existe, por favor verifique</h3>";
                        break;
                 
                    default:
                        # code...
                        break;
                }
            }
            ?>
        </div>
        </div>
        
        <div id="footer">
                <div id="formulario">
                    <li>Equipos</li>
                    <form action="" method=post name="formulario">
                    <label>Id</label>
                    <input type="text" name="Id_requisicion" value="<?php echo $d[0]["Id"]?>" readonly>
                    <br>
                    <label>Producto</label>
                    <input name="producto" type="text" id="fproducto">
                        <br>
                    <label>Cantidad</label>
                    <input type="text" name="cantidad" id="fcantidad">
                    <br>
                    <label>Valor unitario</label>
                    <input type="text" name="vunitario" id="fvu">
                    <br>
                    <label>Impuesto</label>
                    <input type="text" name="impuesto" id="fimp">
                    <br>    
                        <br>
                    <input type="submit" name="guardar" value="Guardar">
                    <input type="hidden" id="f_grabar" name="grabar_formu" value="si">
                    <input type="hidden" name="fid" id="fid" value="">
                    <a href="#" id="cerrar">Cerrar</a>
                </form>
            </div>  
        </div>
        
    </body>
</html>
