<html>
    <head>
        <title>Caja Menor</title>
        <meta charset="utf-8">
        <link rel="shortcut icon" href="http://www.boteroibanez.com/img/botero.ico">
        <link rel="stylesheet" type="text/css" href="<?php echo Conexion::ruta();?>script/estilos/estilos.css"></style>
        <link rel="stylesheet" type="text/css" href="<?php echo Conexion::ruta();?>script/estilos/estilos2.css"></style>
        <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
        <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
        <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
        <link rel="stylesheet" href="/resources/demos/style.css" />
        <script type="text/javascript" src="<?php echo Conexion::ruta();?>/script/js/traduccion.js">
        </script>
        <script type="text/javascript">
            $(function(){
                 $("#logo").click(function(){
                    location.href="<?php echo Conexion::ruta();?>home";
                })
                $( ".datepicker" ).datepicker();

                $("#abrir").click(function(){
                        
                    $("#footer_c,#formulario_c").fadeIn();
                    });//click
                
                $("#cerrar").click(function(){
                    $("#footer_c,#formulario_c").fadeOut();
                    });

                $("#nuevo").click(function(){
                        $("#fproducto").val(" ");
                        $("#fcantidad").val(" ");
                        $("#fvu").val(" ");
                        $("#fimp").val(" ");
                        $("#f_grabar").val(" ");
                    location.href="<?php echo Conexion::ruta()?>Cont_caja?n=1";
                    });
                $("#guardar").click(function(){
                    document.form.submit();
                    });

                $("#Imprimir").click(function(){
                    var id=$("#Id").val();
                    window.open("<?php echo Conexion::ruta()?>view/pdf/pdf_requi.phtml?Requi="+id+"&id_centro=<?php echo $_SESSION["Id_centro"]?>","Impresion" ,"width=700,height=700,scrollbars=NO"); 
                    location.href="<?php echo Conexion::ruta()?>Cont_caja?i="+id;

                })
                $("#estadod").click(function(){
                    alert("estado");
                });

                $("#sucursal").click(function(){
                    alert("sucursal");
                })

                $("#buscar").click(function(){
                    var dato=$("#txtbuscar").val();
                    if(!dato==0){
                    location.href="<?php echo Conexion::ruta()?>Cont_caja?b="+dato;    
                    }
                })

                $("#txtbuscar").keypress(function(event){
                    if(event.which==13){
                        var dato=$("#txtbuscar").val();
                        location.href="<?php echo Conexion::ruta()?>Cont_caja?b="+dato;    
                    }
                });

                $("#botones").click(function(){
		    $("#footer_c,#formulario_c").fadeOut();
                    $("#footer_bot,#formulario_bot").fadeIn();
                 });//ver botones

	        $("#cerrar_bot").click(function(){
	        $("#footer_bot,#formulario_bot").fadeOut();
		$("#footer_c,#formulario_c").fadeIn();
	          });  

              var arregloPersonal=new Array(<?php echo $Proveerdoresb; ?>);
                $( ".personal" ).autocomplete({
                        source: arregloPersonal
                });

                });//main    
        </script>
        <script type="text/javascript">
        function eliminar(id,id_requi){
            if(confirm("Desea eliminar este detalle")){
                location.href="<?php echo Conexion::ruta()?>Cont_caja&e="+id+"&b="+id_requi;
            }
        }
        function editar(id,Con){
            $.post('http://monitoreoelectronicoeia.com/GIO/view/ajax_caja_menor.phtml',{id:id,Con:Con},function(data){
                        $("#footer,#formulario").fadeIn();
                        $("#formulario").html(data);
                    });
        }

        function copiar(id,id_requi){
            if(confirm("Esta seguro copiar esta fila?")){
             location.href="<?php echo Conexion::ruta()?>Cont_caja&Con="+id+"&id="+id_requi;   
            }else{
                $(".ck").removeAttr("checked");
            }
        }

        </script>
    </head>
    <body>
        <div id="header">
            <div id="logo">
                
            </div>
            <div id="menu">
                <?php include"view/Menu.phtml";?>
            </div>

             <div id="sesion">
                <a href="<?php echo Conexion::ruta()?>cerrar" title="Cerrar Sesion"><img class="cerrar_c" src="<?php echo Conexion::ruta()?>images/cerrar.png"></a><br>
                <?php echo ucwords($_SESSION["Nombre"]);?><br>
                <strong><?php echo $centro;?></strong>
            </div>
        </div>
        <div id="linea"></div>
        <form action="" method="POST" name="form">
        <div id="lateral">
            <ul>
                <li><img title="Nuevo" id="nuevo" class="imagen" src="<?php echo Conexion::ruta()?>images/agregar.jpg"></li>
                <li><img title="Guardar" class="imagen" src="<?php echo Conexion::ruta()?>images/guardar.png" id="guardar">
                    <input type="hidden" name="grabar" value="si"></li>
                <li><img title="Imprimir" id="Imprimir" class="imagen" src="<?php echo Conexion::ruta()?>images/impresora.png"></li>
                <li><img title="Buscar" class="imagen" id="buscar" src="<?php echo Conexion::ruta()?>images/buscar.png"></li>
                <li><input type="text" name="txtbuscar" size=10 id="txtbuscar"></li>
            </ul>
        </div>
        <div id="contenido">
            <h2>Caja Menor</h2>
            
            <div class="caja">
               <table>
                <tr>

                    <td><span>Id</span></td>
                    <td><input type="text" name="Id_c" id="Id" value="<?php echo (isset($d[0]["Consecutivo"]))?$d[0]["Consecutivo"]:"";?>" readonly>
                        <input type="hidden" name="Id" id="Id" value="<?php echo $d[0]["Id"]?>" readonly>
                    </td>
                </tr>
                <tr>
                    <td><span>Estadodoc</span></td>
                    <td><input type="text" name="Estadodoc" value="<?php echo (isset($d[0]["Estadodoc"]))?$d[0]["Estadodoc"]:"";?>" readonly></td>
                </tr>
                <tr>
                    <td><span>Fecha Doc</span></td>
                    <td><input type="text" name="Fecha" <?php echo $imp?> class="datepicker" value="<?php echo (isset($d[0]["Fecha"]))?$d[0]["Fecha"]:"";?>"></td>
                </tr>

            </table>
          
            </div>
            
            <div class="caja">
               <table>
                <tr>
                    <td><span>No Doc Reembolso</span></td>
                    <td><input type="text" name="Nodocrem" <?php echo $imp?> value="<?php echo (isset($d[0]["Nodocrem"]))?$d[0]["Nodocrem"]:"";?>"></td>
                </tr>
                <tr>
                    <td><span>Cod Contable</span></td>
                    <td><input type="text" name="Codcontable" <?php echo $imp?> value="<?php echo (isset($d[0]["Codcontable"]))?$d[0]["Codcontable"]:"";?>"></td>
                </tr>
                <tr>
                    <td><span>No caja(sistema)</span></td>
                    <td><input type="text" name="Nocajasis" <?php echo $imp?> value="<?php echo (isset($d[0]["Nocajasis"]))?$d[0]["Nocajasis"]:"";?>"></td>
                </tr>
                <tr>
                    <td><span>V Sin iva</span></td>
                    <td><input type="text" name="Vantesiva" readonly <?php echo $imp?> value="<?php echo (isset($d[0]["Vantesiva"]))?$d[0]["Vantesiva"]:"";?>"></td>
                </tr>

                 </table>   
            </div>
            <div class="caja">
                
                 <table>    
                
                <tr>
                    <td><span>V iva</span></td>
                    <td><input type="text" name="Viva" <?php echo $imp?> value="<?php echo (isset($d[0]["Viva"]))?$d[0]["Viva"]:"";?>"></td>
                </tr>
                <tr>
                    <td><span>V Total</span></td>
                    <td><input type="text" name="Vtotal" readonly <?php echo $imp?> value="<?php echo (isset($d[0]["Vtotal"]))?$d[0]["Vtotal"]:"";?>"></td>
                </tr>
                <tr>
                    <td><span>Observaciones</span></td>
                    <td><textarea name="Observaciones" <?php echo $imp?> ><?php echo (isset($d[0]["Observaciones"]))?$d[0]["Observaciones"]:"";?></textarea></td>
                </tr>
                 </table>   
            </div>
            <div id="boton">
            <a href="#" id="abrir" style="color: rgb(0,43,87);"><img title="Agregar Detalle" id="nuevo" class="imagen" src="<?php echo Conexion::ruta()?>images/detalle.png"></a>
            </div>
            </form>      
            <div id="tabla">

            <table align="center" class="bordered">
                <thead>
                    <th>Centro costo</th>
                    <th>No Rem</th>
                    <th>Fecha Rem</th>
		    <th>Nit-Rut</th>
                    <th>Cuenta O Cod</th>
                    <th>Valor Debito</th>
                    <th>Base Retencion</th>
                    <th>V Retencion</th>
                    <th>Base Iva</th>
                    <th>V Iva</th>
		    <th>Concepto</th>
		    <th>Cuenta Iva</th>
		    <th>Curetencion</th>
                    <th>Editar</th>
                    <th>Eliminar</td>
                    <th>Copiar</td>
                </thead>
                
                    <?php
                    for($i=0;$i<sizeof($detalle);$i++){
                        ?>
                        <tr align="center">
                            <td><?php echo $detalle[$i]["Centrocosto"]?></td>
                            <td><?php echo $detalle[$i]["Norembolso"]?></td>
                            <td><?php echo $detalle[$i]["FechaRembolso"]?></td>
			    <td><?php echo $detalle[$i]["Nit"]?></td>
                            <td><?php echo $detalle[$i]["Cuentaocod"]?></td>
                            <td><?php echo $detalle[$i]["Valordebito"]?></td>
                            <td><?php echo $detalle[$i]["Basederetencion"]?></td>
                            <td><?php echo $detalle[$i]["Vderetencion"]?></td>
                            <td><?php echo $detalle[$i]["Baseiva"]?></td>
                            <td><?php echo $detalle[$i]["Viva"]?></td>
                            <td><?php echo $detalle[$i]["Concepto"]?></td>
                            <td><?php echo $detalle[$i]["Cuiva"]?></td>
                            <td><?php echo $detalle[$i]["Curetencion"]?></td>
                            <td><img title="Editar" class="icono2" src="<?php echo Conexion::ruta()?>images/editar.jpg" onclick="editar('<?php echo $detalle[$i]["Id"]?>','<?php echo $detalle[$i]["Id_cm"]?>')"> 
                            </td>
                            <td><img title="Eliminar" class="icono2" src="<?php echo Conexion::ruta()?>images/eliminar.png" onclick="eliminar('<?php echo $detalle[$i]["Id"]?>','<?php echo $detalle[$i]["Id_cm"]?>')"></td>
                            <td align="center">
                                    <input type="checkbox" class="ck" onclick="copiar('<?php echo $detalle[$i]["Id"]?>','<?php echo $detalle[$i]["Id_cm"]?>');">
                                </div>
                            </td>
                        </tr>        
                        <?php
                    }
                    ?>  
            </table>
        </div>

        </div>

        <div id="footer_c">
                <div id="formulario_c">
                    <li>Caja Menor</li>
                    <form action="" method=post name="formulario">
                    <table>
                        <tr>
                            <td><span class="letra">Id</span></td>
                            <td><input type="text" name="Id_c" class="ent2" value="<?php echo (isset($d[0]["Consecutivo"]))?$d[0]["Consecutivo"]:"";?>" readonly></td>
                            <td><span class="letra">No rembolso</span></td>
                            <td><input type="text" name="Norembolso" class="ent2" 
                        </tr>    
                        <tr>
			    <td><span class="letra">Fecha Rembolso</span></td>
                            <td><input name="FechaRembolso" type="text" class="ent2 datepicker"></td>
                            <td><span class="letra">Nit-Rut</span></td>
                            <td><input type="text" name="Nit" class="ent2 personal">
			    <img title="Ver iconos" class="imagen2" style="cursor:pointer" id="botones" src="<?php echo Conexion::ruta()?>images/adelante.png">
			    </td>
                        </tr>
                        <tr>
                            <td><span class="letra">Cuentaocod</span></td>
                            <td><input type="text" name="Cuentaocod" class="ent2"></td>
                            <td><span class="letra">Valordebito</span></td>
                            <td><input type="text" name="Valordebito" class="ent2"></td>
                        </tr>
                        <tr>
                            <td><span class="letra">Basederetencion</span></td>
                            <td><input type="text" name="Basederetencion" class="ent2"></td>
                            <td><span class="letra">Baseiva</span></td>
                            <td><input type="text" name="Baseiva" class="ent2"></td>
                        </tr>
                        <tr>
                            <td><span class="letra">Concepto</span></td>
                            <td><input type="text" name="Concepto" class="ent2"></td>
                            <td><span class="letra">Cuenta Iva</span></td>
                            <td><input type="text" name="Cuiva" class="ent2"></td>
                        </tr>
                        <tr>
                            <td><span class="letra">Cuenta Ret</span></td>
                            <td><input type="text" name="Curetencion" class="ent2"></td>
                        </tr>
                        <tr align="center">
                            <td colspan="4"><input type="submit" name="guardar" value="Guardar">
                    <input type="hidden" id="f_grabar" id name="grabar_formu" value="si">
                    <input type="hidden" name="Id" value="<?php echo $d[0]["Id"]?>">
                    <a href="#" id="cerrar">Cerrar</a>
                </td>
                        </tr>

                    </table>
                    
                    
                    
                    
                </form>
            </div>  
        </div>

	<div id="footer_bot">
                <div id="formulario_bot">
		    <img title="Agregar Pagos"  class="imagen3" id="pagos" src="<?php echo Conexion::ruta()?>images/pagos.png">
                    <br>
                    <br>
                    <a href="#" id="cerrar_bot">Cerrar</a>   
                </div>
        </div>

        <div id="ajax"></div>
    </body>
</html>

