<html>
    <head>
        <title>Registro</title>
        <meta charset="utf-8">
        <link rel="stylesheet" type="text/css" href="<?php echo Conexion::ruta();?>script/estilos/estilos.css"></style>
        <script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>
        <script type="text/javascript">
            $(function(){
                
                
                });//main    
        </script>
    </head>
    <body>
        <div id="header">
            <div id="logo">
                
            </div>
            <div id="menu">
                <?php include"view/Menu.phtml";?>
            </div>
        </div>
        <div id="linea"></div>
        <div id="lateral"></div>
        <div id="contenido">
            <br>
            <h1>Recordar Clave</h1>
            <form action="" method="POST" name="form">
                <table align="center">
                    <tr>
                        <td>Usuario</td>
                        <td><input type="text" name="usuario"></td>
                    </tr>
                    <tr>
                        <td>Correo</td>
                        <td><input type="text" name="correo"></td>
                    </tr>
                    
                    <tr align="center">
                        <td colspan="2"><input type="submit" name="Ingresar" value="Registrar">
                        <input type="hidden" name="grabar" value="si">
                        </td>
                    </tr>
                    <tr>
                        <td><br></td>
                    </tr>
                    <tr align="center">
                        <td colspan="2"><a href="<?php echo Conexion::ruta()?>login">volver</a></td>
                    </tr>
                </table>
            
            </form>      
        
        </div>
        <div id="footer">
                
        </div>
    </body>
</html>