<html>
    <head>
        <title>QHSE</title>
        <link rel="shortcut icon" href="http://www.boteroibanez.com/img/botero.ico">
        <link rel="stylesheet" type="text/css" href="<?php echo Conexion::ruta();?>script/estilos/estilos.css"></style>
        <link rel="stylesheet" type="text/css" href="<?php echo Conexion::ruta();?>script/estilos/estilos2.css"></style>
        <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
        <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
        <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
        <link rel="stylesheet" href="/resources/demos/style.css" />
        <script type="text/javascript">
            $(function(){
                 $("#logo").click(function(){
                    location.href="<?php echo Conexion::ruta();?>home";
                })
                $( "#datepicker" ).datepicker();

                $("#abrir").click(function(){
                        
                    $("#footer,#formulario").fadeIn();
                    });//click
                
                $("#cerrar").click(function(){
                    $("#footer,#formulario").fadeOut();
                    });

                $("#nuevo").click(function(){
                        $("#fproducto").val(" ");
                        $("#fcantidad").val(" ");
                        $("#fvu").val(" ");
                        $("#fimp").val(" ");
                        $("#f_grabar").val(" ");
                    location.href="<?php echo Conexion::ruta()?>Requisicion&n=1";
                    });
                $("#guardar").click(function(){
                    document.form.submit();
                    });

                $("#Imprimir").click(function(){
                    var id=$("#Id").val();
                    window.open("<?php echo Conexion::ruta()?>view/pdf/pdf_requi.phtml?Requi="+id+"&id_centro=<?php echo $_SESSION["Id_centro"]?>","Impresion" ,"width=700,height=700,scrollbars=NO"); 
                    location.href="<?php echo Conexion::ruta()?>Requisicion&i="+id;

                })
                $("#estadod").click(function(){
                    alert("estado");
                });

                $("#sucursal").click(function(){
                    alert("sucursal");
                })

                $("#buscar").click(function(){
                    var dato=$("#txtbuscar").val();
                    if(!dato==0){
                    location.href="<?php echo Conexion::ruta()?>Requisicion&b="+dato;    
                    }
                })

                $("#txtbuscar").keypress(function(event){
                    if(event.which==13){
                        var dato=$("#txtbuscar").val();
                        location.href="<?php echo Conexion::ruta()?>Requisicion&b="+dato;    
                    }
                });

                });//main    
        </script>
        <script type="text/javascript">
        function eliminar(id,id_requi){
            if(confirm("Desea eliminar este detalle")){
                location.href="<?php echo Conexion::ruta()?>Requisicion&e="+id+"&b="+id_requi;
            }
        }
        function editar(id,requi,producto,cantidad,Vu,imp){
            $("#fproducto").val(producto);
            $("#fcantidad").val(cantidad);
            $("#fvu").val(Vu);
            $("#fimp").val(imp);
            $("#f_grabar").val("si2");
            $("#fid").val(id);
            $("#footer,#formulario").fadeIn();
        }

        function copiar(id,id_requi){
            if(confirm("Esta seguro copiar esta fila?")){
             location.href="<?php echo Conexion::ruta()?>Requisicion&Con="+id+"&id="+id_requi;   
            }else{
                $(".ck").removeAttr("checked");
            }
        }

        </script>
    </head>
    <body>
        <div id="header">
            <div id="logo">
                
            </div>
            <div id="menu">
                <?php include"view/Menu.phtml";?>
            </div>

             <div id="sesion">
                <a href="<?php echo Conexion::ruta()?>cerrar" title="Cerrar Sesion"><img class="cerrar_c" src="<?php echo Conexion::ruta()?>images/cerrar.png"></a><br>
                <?php echo ucwords($_SESSION["Nombre"]);?><br>
                <strong><?php echo $centro;?></strong>
            </div>
        </div>
        <div id="linea"></div>
        <div id="espacio"></div>
        <form action="" method="POST" name="form">
        <div id="lateral">
            <ul>
                <li><img title="Nuevo" id="nuevo" class="imagen" src="<?php echo Conexion::ruta()?>images/agregar.jpg"></li>
                <li><img title="Guardar" class="imagen" src="<?php echo Conexion::ruta()?>images/guardar.png" id="guardar">
                    <input type="hidden" name="grabar" value="si"></li>
                <li><img title="Imprimir" id="Imprimir" class="imagen" src="<?php echo Conexion::ruta()?>images/impresora.png"></li>
                <li><img title="Buscar" class="imagen" id="buscar" src="<?php echo Conexion::ruta()?>images/buscar.png"></li>
                <li><input type="text" name="txtbuscar" size=10 id="txtbuscar"></li>
            </ul>
        </div>
        <div id="contenido">
            <h2>QHSE</h2>
            
            <div class="caja">
               <table>
                <tr>

                    <td><span>Id</span></td>
                    <td><input type="text" name="Id" id="Id" value="<?php echo (isset($d[0]["Consecutivo"]))?$d[0]["Consecutivo"]:"";?>" readonly></td>
                </tr>
                <tr>
                    <td><span>Estadodoc</span></td>
                    <td><input type="text" name="Estadodoc" value="<?php echo (isset($d[0]["Lista"]))?$d[0]["Lista"]:"";?>" readonly></td>
                    
                </tr>
                <tr>
                    <td><span>Festadodoc</span></td>
                    <td><input type="text" name="Festadodoc" <?php echo $imp?> value="<?php echo (isset($d[0]["Fr"]))?$d[0]["Fr"]:"";?>"></td>
                </tr>
                <tr>
                    <td><span>PersonaSolicito</span></td>
                    <td><input type="text" name="Ps" <?php echo $imp?> value="<?php echo (isset($d[0]["Ps"]))?$d[0]["Ps"]:"";?>"></td>
                </tr>
            </table>
          
            </div>
            
            <div class="caja">
               <table>
                    <tr>
                    <td><span>Sucursal</span></td>
                    <td><input type="text" name="Sucursal" <?php echo $imp?> value="<?php echo (isset($d[0]["Sucursal"]))?$d[0]["Sucursal"]:"";?>"></td>
                </tr>
                <tr>
                    <td><span>Centrocosto</span></td>
                    <td><input type="text" name="Centrocosto" <?php echo $imp?> value="<?php echo (isset($d[0]["Centro_costo"]))?$d[0]["Centro_costo"]:"";?>"></td>
                </tr>
                <tr>
                    <td><span>Fentrega</span></td>
                    <td><input type="text" name="Fentrega" id="datepicker" <?php echo $imp?> value="<?php echo (isset($d[0]["Fentrega"]))?$d[0]["Fentrega"]:"";?>"></td>
                </tr>
                 </table>   
            </div>
            <div class="caja">
                
                 <table>    
                    <tr>
                    <td><span>Lentrega</span></td>
                    <td><input type="text" name="Lentrega" <?php echo $imp?> value="<?php echo (isset($d[0]["Lentrega"]))?$d[0]["Lentrega"]:"";?>"></td>
                </tr>
                <tr>
                    <td><span>Estadoproceso</span></td>
                    <td><input type="text" name="Estadoproceso" <?php echo $imp?>></td>
                </tr>
                <tr>
                    <td><span>Observaciones</span></td>
                    <td><textarea name="Observaciones" <?php echo $imp?>><?php echo (isset($d[0]["Observaciones"]))?$d[0]["Observaciones"]:"";?></textarea></td>
                </tr>
                 </table>   
            </div>
            <div id="boton">
            <a href="#" id="<?php echo $bt;?>" style="color: rgb(0,43,87);"><img title="Agregar Detalle" id="nuevo" class="imagen" src="<?php echo Conexion::ruta()?>images/detalle.png"></a>
            </div>
            </form>      
            <div id="tabla">

            <table align="center" class="bordered">
                <thead>
                    <th>Producto</th>
                    <th>Cantidad</th>
                    <th>Vunitario</th>
                    <th>Impuesto</th>
                    <th>Vneto</th>
                    <th>Vtotal</th>
                    <th>Editar</th>
                    <th>Eliminar</td>
                    <th>Copiar</td>
                </thead>
                
                    <?php
                    for($i=0;$i<sizeof($detalle);$i++){
                        ?>
                        <tr align="center">
                            <td><?php echo $detalle[$i]["Producto"]?></td>
                            <td><?php echo $detalle[$i]["Cantidad"]?></td>
                            <td><?php echo $detalle[$i]["Vu"]?></td>
                            <td><?php echo $detalle[$i]["Imp"]?></td>
                            <td><?php echo "$ ".number_format($detalle[$i]["Vn"],3,",",".")?></td>
                            <td><?php echo "$ ".number_format($detalle[$i]["Vt"],3,",",".")?></td>
                            <td><img title="Editar" class="icono2" src="<?php echo Conexion::ruta()?>images/editar.jpg" onclick="editar('<?php echo $detalle[$i]["Id"]?>','<?php echo $detalle[$i]["Id_Requisicion"]?>','<?php echo $detalle[$i]["Producto"]?>','<?php echo $detalle[$i]["Cantidad"]?>','<?php echo $detalle[$i]["Vu"]?>','<?php echo $detalle[$i]["Imp"]?>')"> 
                            </td>
                            <td><img title="Eliminar" class="icono2" src="<?php echo Conexion::ruta()?>images/eliminar.png" onclick="eliminar('<?php echo $detalle[$i]["Id"]?>','<?php echo $detalle[$i]["Id_Requisicion"]?>')"></td>
                            <td align="center">
                                    <input type="checkbox" class="ck" onclick="copiar('<?php echo $detalle[$i]["Id"]?>','<?php echo $detalle[$i]["Id_Requisicion"]?>');">
                                </div>
                            </td>
                        </tr>        
                        <?php
                    }
                    ?>  
            </table>
        </div>

        </div>
        
        <div id="footer">
                <div id="formulario">
                    <li>Menu principal</li>
                    <form action="" method=post name="formulario">
                    <?php
                    foreach ($prin as $key => $value) {
                    if($prin[$key]["id_menu"]==$principal[$key]["id_menu"]){
                    ?>
                    <ul>
                        <li><input type="checkbox" checked value="<?php echo $prin[$key]['id_menu']?>" name="principal[]"><?php echo $prin[$key]["principal"]?></li>
                    </ul>
                    <?php
                    }else{
                    ?>
                    <ul>
                        <li><input type="checkbox" value="<?php echo $prin[$key]['id_menu']?>" name="principal[]"><?php echo $prin[$key]["principal"]?></li>
                    </ul>
                    <?php
                    }
                }
                ?>
                    <br>    
                        <br>
                    <input type="submit" name="guardar" value="Guardar">
                    <input type="hidden" id="f_grabar" id name="grabar_formu" value="si">
                    <input type="hidden" name="fid" id="fid" value="">
                    <a href="#" id="cerrar">Cerrar</a>
                </form>
            </div>  
        </div>
        
    </body>
</html>

