<html>
    <head>
        <title>Salidas</title>
        <meta charset="utf-8">
        <link rel="shortcut icon" href="http://www.boteroibanez.com/img/botero.ico">
        <link rel="stylesheet" type="text/css" href="<?php echo Conexion::ruta();?>script/estilos/estilos.css"></style>
        <link rel="stylesheet" type="text/css" href="<?php echo Conexion::ruta();?>script/estilos/estilos2.css"></style>
        <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
        <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
        <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
        <link rel="stylesheet" href="/resources/demos/style.css" />
        <script type="text/javascript">
            $(function(){
                 $("#logo").click(function(){
                    location.href="<?php echo Conexion::ruta();?>home";
                })
                $( "#datepicker" ).datepicker();

                $("#abrir").click(function(){
                        
                    $("#footer,#formulario").fadeIn();
                    });//click
                
                $("#cerrar").click(function(){
                    $("#footer,#formulario").fadeOut();
                    })
                $("#nuevo").click(function(){
                        $("#fproducto").val(" ");
                        $("#fcantidad").val(" ");
                        $("#fvu").val(" ");
                        $("#fimp").val(" ");
                        $("#f_grabar").val(" ");
                    location.href="<?php echo Conexion::ruta()?>Salidas&n=1";
                    });


                $("#guardar").click(function(){
                        if($("#activo").is(":checked")){
                            document.form.submit();
                        }else{
                            if(confirm("Esta salida no tiene Requisicion, desea continuar")){
                                document.form.submit();
                            }
                        }
                            
                    });

                $("#estadod").click(function(){
                    alert("estado");
                });

                $("#Imprimir").click(function(){
                    var id=$("#Id").val();
                     window.open("<?php echo Conexion::ruta()?>view/pdf/pdf_requi.phtml?Salida="+id+"&id_centro=<?php echo $_SESSION["Id_centro"]?>","Impresion" ,"width=700,height=700,scrollbars=NO"); 
                    location.href="<?php echo Conexion::ruta()?>Salidas&i="+id;
                });

                $("#sucursal").click(function(){
                    alert("sucursal");
                })

                $("#buscar").click(function(){
                    var dato=$("#txtbuscar").val();
                    location.href="<?php echo Conexion::ruta()?>Salidas?b="+dato;

                })

                $("#txtbuscar").keypress(function(event){
                    if(event.which==13){
                        var dato=$("#txtbuscar").val();
                        location.href="<?php echo Conexion::ruta()?>Salidas?b="+dato;
                    }
                });

                $("#activo").click(function(){
                    if($("#activo").is(":checked")){
                        $("#Requisicion").removeAttr("disabled");
                    }else{
                        $("#Requisicion").attr("disabled",true);
                    }    
                })


                var availableTags4=new Array(<?php echo $proyectos; ?>);
                $( "#Proyecto" ).autocomplete({
                        source: availableTags4
                });

                var availableTags=new Array(<?php echo $personales; ?>);
                $( "#EntregadoA" ).autocomplete({
                        source: availableTags
                });

                var availableTags2=new Array(<?php echo $productos; ?>);
                $( "#producto" ).autocomplete({
                        source: availableTags2
                });

                });//main    
        </script>
        <script type="text/javascript">
        function eliminar(id,id_requi){
            if(confirm("Desea eliminar este detalle")){
                location.href="<?php echo Conexion::ruta()?>Salidas&e="+id+"&b="+id_requi;
            }
        }
        function editar(id,requi,producto,cantidad,Vu,imp){
            $("#producto").val(producto);
            $("#fcantidad").val(cantidad);
            $("#fvu").val(Vu);
            $("#fimp").val(imp);
            $("#f_salidas").val("si2");
            $("#fid").val(id);
            $("#footer,#formulario").fadeIn();
            
        }

        function copiar(id,id_requi){
            if(confirm("Esta seguro copiar esta fila?")){
             location.href="<?php echo Conexion::ruta()?>Salidas&Con="+id+"&id="+id_requi;   
            }else{
                $(".ck").removeAttr("checked");
            }
        }

        </script>
    </head>
    <body>
        <div id="header">
            <div id="logo">
                
            </div>
            <div id="menu">
                <?php include"view/Menu.phtml";?>
            </div>
             <div id="sesion">
            <a href="<?php echo Conexion::ruta()?>cerrar"><img class="cerrar_c" src="<?php echo Conexion::ruta()?>images/cerrar.png"></a><br>
            <?php echo ucwords($_SESSION["Nombre"]);?><br>
                <strong><?php echo $centro;?></strong>
            </div>
        </div>
        <div id="linea"></div>
        <div id="espacio"></div>
        <form action="" method="POST" name="form">
        <div id="lateral">
            <ul>
                <li><img title="Nuevo" id="nuevo" class="imagen" src="<?php echo Conexion::ruta()?>images/agregar.jpg"></li>
                <li><img title="Guardar" class="imagen" src="<?php echo Conexion::ruta()?>images/guardar.png" id="guardar">
                    <input type="hidden" name="grabar" id="grabar" value="si"></li>
                <li><img title="Imprimir" id="Imprimir" class="imagen" src="<?php echo Conexion::ruta()?>images/impresora.png"></li>
                <li><img title="Buscar" class="imagen" id="buscar" src="<?php echo Conexion::ruta()?>images/buscar.png"></li>
                <li><input type="text" name="txtbuscar" size=10 id="txtbuscar"></li>
            </ul>
        </div>
        <div id="contenido">
            <h2>Salidas</h2>
            
            <div class="caja">
               <table>
                <tr>
                    <td><span>Id</span></td>
                    <td><input type="text" name="Id" id="Id" class="tam" value="<?php echo (isset($d[0]["Consecutivo"]))?$d[0]["Consecutivo"]:"";?>" readonly></td>
                </tr>
                <tr>
                    <td><span>Estadodoc</span></td>
                    <td><input type="text" name="Estadodoc" class="tam" value="<?php echo (isset($d[0]["Lista"]))?$d[0]["Lista"]:"";?>" readonly></td>
                </tr>
                <tr>
                    <td><span>Festadodoc</span></td>
                    <td><input type="text" <?php echo (isset($imp))?$imp:"";?> class="tam" name="Festadodoc" value="<?php echo (isset($d[0]["Fr"]))?$d[0]["Fr"]:"";?>" readonly></td>
                </tr>
                <tr>
                    <td><span>EntregadoA</span></td>
                    <td><input type="text" <?php echo (isset($imp))?$imp:"";?> class="tam" id="EntregadoA" name="EntregadoA" value="<?php echo (isset($d[0]["EntregadoA"]))?$d[0]["EntregadoA"]:"";?>"></td>
                </tr>
                
            </table>
          
            </div>
            
            <div class="caja">
               <table>
                <tr>
                    <td><span>Sucursal</span></td>
                    <td><input type="text" name="Sucursal" class="tam" <?php echo (isset($imp))?$imp:"";?> value="<?php echo (isset($d[0]["Sucursal"]))?$d[0]["Sucursal"]:"";?>" readonly></td>
                </tr>
                <tr>
                    <td><span>CentroCosto</span></td>
                    <td><input type="text" name="Centro" class="tam" <?php echo (isset($imp))?$imp:"";?> value="<?php echo (isset($d[0]["Centro_costo"]))?$d[0]["Centro_costo"]:"";?>" readonly></td>
                </tr>
                <tr>
                    <td><span>Proyecto</span></td>
                    <td><input type="text" name="Proyecto" id="Proyecto" class="tam" <?php echo (isset($imp))?$imp:"";?> value="<?php echo (isset($d[0]["Proyecto"]))?$d[0]["Proyecto"]:"";?>"></td>
                </tr>
                <tr>
                    <td><span>No Requisición</span></td>
                    <td><input type="text" name="Requisicion" class="tam" id="Requisicion" <?php echo ($d["0"]["Requisicion"]) > 0?"":"disabled"; ;?>
                        <?php echo (isset($imp))?$imp:"";?> value="<?php echo (isset($d[0]["Requisicion"]))?$d[0]["Requisicion"]:"";?>"></td>
                    <td><input type="checkbox" name="activo" <?php echo ($d[0]["Requisicion"])>0 ?"checked":""; ;?> id="activo"></td>
                </tr>
               
                 </table>   
            </div>
            <div class="caja">
                 <table>    
                        <tr>
                    <td><span>Tipo</span></td>
                    <td>
                        <select name="Tipo" <?php echo (isset($imp))?$imp:"";?> class="tam">
                            <option value="0">Seleccione</option>
                            <?php
                            foreach ($listas as $k => $valor) {
                                if($listas[$k]["Numeracion"]==$d[0]["Tipo"]){
                                 ?>
                                    <option selected="selected" value="<?php echo $listas[$k]['Numeracion']?>"><?php echo $listas[$k]["Lista"]?></option>   
                                 <?php   
                                }else{
                                ?>
                                    <option value="<?php echo $listas[$k]['Numeracion']?>"><?php echo $listas[$k]["Lista"]?></option>
                                <?php        
                                }
                            }
                            ?>
                        </select>
                    </td>
                    
                </tr>
                <tr>
                    <td><span>Destino</span></td>
                    <td>
                        <select name="Destino" <?php echo (isset($imp))?$imp:"";?> class="tam">
                            <option value="0">Seleccione</option>
                            <?php
                            foreach ($destino as $a => $valor) {
                                if($destino[$a]["Numeracion"]==$d[0]["Destino"]){
                                 ?>
                                    <option selected="selected" value="<?php echo $destino[$a]['Numeracion']?>"><?php echo $destino[$a]["Lista"]?></option>   
                                 <?php   
                                }else{
                                ?>
                                    <option value="<?php echo $destino[$a]['Numeracion']?>"><?php echo $destino[$a]["Lista"]?></option>
                                <?php        
                                }
                            }
                            ?>
                        </select>
                    </td>
                </tr>
                    <tr>
                        <td><span>Observaciones</span></td>
                        <td><textarea name="Observaciones" <?php echo (isset($imp))?$imp:"";?> class="tam"><?php echo (isset($d[0]["Observaciones"]))?$d[0]["Observaciones"]:"";?></textarea></td>
                    </tr>
                 </table>   
            </div>
            <div id="boton">
            <a href="#" id="<?php echo $bt;?>" style="color: rgb(0,43,87);"><img title="Agregar Detalle" id="nuevo" class="imagen" src="<?php echo Conexion::ruta()?>images/detalle.png"></a>
            </div>
            </form>      
            
            <div id="tabla">

            <table align="center" class="bordered">
                <thead>
                    <th>Producto</th>
                    <th>Cantidad</th>
                    <th>Vunitario</th>
                    <th>Impuesto</th>
                    <th>Vneto</th>
                    <th>Vtotal</th>
                    <th>Editar</th>
                    <th>Eliminar</td>
                    <th>Copiar</td>
                </thead>
                
                    <?php
                    for($i=0;$i<sizeof($detalle);$i++){
                        ?>
                        <tr>
                            <td><?php echo $detalle[$i]["Producto"]?></td>
                            <td><?php echo $detalle[$i]["Cantidad"]?></td>
                            <td><?php echo $detalle[$i]["Vu"]?></td>
                            <td><?php echo $detalle[$i]["Imp"]?></td>
                            <td><?php echo "$ ".number_format($detalle[$i]["Vn"],3,",",".")?></td>
                            <td><?php echo "$ ".number_format($detalle[$i]["Vt"],3,",",".")?></td>
                            <td><img title="Editar" class="icono2" src="<?php echo Conexion::ruta()?>images/editar.jpg" onclick="editar('<?php echo $detalle[$i]["Id"]?>','<?php echo $detalle[$i]["Id_sal"]?>','<?php echo $detalle[$i]["Producto"]?>','<?php echo $detalle[$i]["Cantidad"]?>','<?php echo $detalle[$i]["Vu"]?>','<?php echo $detalle[$i]["Imp"]?>')"></td>
                            <td><img title="Eliminar" class="icono2" src="<?php echo Conexion::ruta()?>images/eliminar.png" onclick="eliminar('<?php echo $detalle[$i]["Id"]?>','<?php echo $detalle[$i]["Id_sal"]?>')"></td>
                            <td><input type="checkbox" class="ck" onclick="copiar('<?php echo $detalle[$i]["Id"]?>','<?php echo $detalle[$i]["Id_sal"]?>');"></td>
                        </tr>        
                        <?php
                    }
                    ?>
                    
            </table>
        </div>
        <div id="paginador">
             <?php
            if(isset($_GET["error"])){
                switch ($_GET["error"]) {
                    case '1':
                        echo "<h3 style='color:red'>El Producto no esta registrado, por favor verifique</h3>";
                        break;
                    case '2':
                        echo "<h3 style='color:red'>El Producto o la persona de entrega tiene errores, por favor verifique</h3>";
                        break;
                    case '3':
                        echo "<h3 style='color:red'>Error en la cantidad de productos, por favor verifique</h3>";
                        break;
                    case '4':
                        echo "<h3 style='color:red'>La Requisicion no existe, por favor verifique</h3>";
                        break;
                    default:
                        # code...
                        break;
                }
            }
            ?>
        </div>

        </div>
        
        <div id="footer">
                <div id="formulario">
                    <li>Salidas</li>
                    <form action="" method=post name="formulario">
                    <label>Id</label>
                    <input type="text" name="Id_sal" value="<?php echo $d[0]["Consecutivo"]?>" readonly>
                    <br>
                    <label>Producto</label>
                    <input name="producto" type="text" id="producto">
                        <br>
                    <label>Cantidad</label>
                    <input type="text" name="cantidad" id="fcantidad">
                    <br>
                    <label>Valor unitario</label>
                    <input type="text" name="vunitario" id="fvu">
                    <br>
                    <label>Impuesto</label>
                    <input type="text" name="impuesto" id="fimp">
                    <br>    
                        <br>
                    <input type="submit" name="guardar" value="Guardar">
                    <input type="hidden" id="f_salidas" name="f_salidas" value="si">
                    <input type="hidden" id="Requi" name="Requi" value="<?php echo $d[0]['Requisicion']?>">
                    <input type="hidden" name="fid" id="fid" value="">
                    <a href="#" id="cerrar">Cerrar</a>
                </form>
            </div>  
        </div>
        
    </body>
</html>
